echo "PPPPP   EEEEE   PPPP   EEEEE    Y   Y    M     M  III  TTTTTT  ZZZZZ    Y   Y"
echo "P    P  E       P   P  E        Y   Y    MM   MM   I      T       Z     Y   Y"
echo "PPPPP   EEEEE   PPPP   EEEEE     Y Y     M M M M   I      T      Z       Y Y"
echo "P       E       P      E          Y      M  M  M   I      T     Z         Y"
echo "P       EEEEE   P      EEEEE      Y      M     M  III     T    ZZZZZ      Y"
